// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -D Default -D PartialEq -A -d -f config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
// kopium version: 0.21.1

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use schemars::JsonSchema;
    pub use serde::{Serialize, Deserialize};
    pub use std::collections::BTreeMap;
}
use self::prelude::*;

/// GeneratePatchesRequestItem represents a template to generate patches for.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct GeneratePatchesRequestItems {
    /// holderReference is a reference to the object where the template is used.
    #[serde(rename = "holderReference")]
    pub holder_reference: GeneratePatchesRequestItemsHolderReference,
    /// object contains the template as a raw object.
    pub object: BTreeMap<String, serde_json::Value>,
    /// uid is an identifier for this template. It allows us to correlate the template in the request
    /// with the corresponding generated patches in the response.
    pub uid: String,
    /// variables are variables specific for the current template.
    /// For example some builtin variables like MachineDeployment replicas and version are context-sensitive
    /// and thus are only added to templates for MachineDeployments and with values which correspond to the
    /// current MachineDeployment.
    pub variables: Vec<GeneratePatchesRequestItemsVariables>,
}

/// holderReference is a reference to the object where the template is used.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct GeneratePatchesRequestItemsHolderReference {
    /// apiVersion of the referent.
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    /// fieldPath is the path to the field of the object which references the template.
    #[serde(rename = "fieldPath")]
    pub field_path: String,
    /// kind of the referent.
    /// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    pub kind: String,
    /// name of the referent.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    pub name: String,
    /// namespace of the referent.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
    pub namespace: String,
}

/// Variable represents a variable value.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct GeneratePatchesRequestItemsVariables {
    /// name of the variable.
    pub name: String,
    /// value of the variable.
    pub value: serde_json::Value,
}

/// Variable represents a variable value.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct GeneratePatchesRequestVariables {
    /// name of the variable.
    pub name: String,
    /// value of the variable.
    pub value: serde_json::Value,
}

